### ISSUE TITLE
image title is not showing in mixedgallery version

### ISSUE THREAD

**Issue by freshcoffee** [ddrayne/youtubeplaylist#2]
first of all, your code is perfect for me. thank you for your contribution.
i just downloaded the code and tried to use mixedgallery version.
everything is working as promised, but just one thing doesn't seem to like working.

with your sample, mixedgallery.html, there are images named "van gogh", "Yo", and "Test2" btw "a href.." and "/a" but it doesn't show up in the screen. 
youtube title are showing ok when i put it btw a href and /a.

am i missing something?

can you advise me on this?

thank you in advance.

**Comment by ddrayne** [comment]
Hey there - thanks for the kind words. 

The plugin is a little rough around the edges, but in order to keep the titles for e.g. image links, you'll see in line 192

``` js
$link.empty().html($img).attr("title", replacedText);
```

The empty() is dropping the html before adding the image, so you could do something like

``` js
$link.append($img).attr("title", replacedText);
```

to add the image at the end, or prepend to insert the image before the text.

The same goes for the youtube thumbnails at line 186.

Hope this helps!

Dan

**Comment by freshcoffee** [comment]
awesome, it works. i didn't adjust the code for youtube thumbnail since it seemed to works ok.
thank you very much.

by the way, this is my link, just in case you might want to see how your work is doing with other people 
http://shareworship.net/tutorials
